language: node_js
node_js:
  - "4"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install -g bower"
  - "npm install -g gulp"
  - "bower install"

# whitelist - only build these branches
branches:
  only:
    - master
    - develop
